"""
Team Dashboard (local clone)
=============================
A local Streamlit clone of the team's online "Team Dashboard" — same layout,
tabs, charts and tables, but reading from a local, swappable data source
instead of an online one.

Run with:
    streamlit run app.py

See data.py for how to plug in your own manually-entered data later.
"""
from __future__ import annotations

import base64
import os
from datetime import datetime, timedelta

import pandas as pd
import streamlit as st

import charts
import data
import store
import theme

st.set_page_config(
    page_title="Team Dashboard",
    page_icon="🎮",
    layout="wide",
    initial_sidebar_state="expanded",
)
theme.inject()

ASSETS_AVATARS = "assets/avatars"
ASSETS_PLAYERS = "assets/players"


def avatar_path(folder: str, name: str) -> str | None:
    p = os.path.join(folder, f"{name}.png")
    return p if os.path.exists(p) else None


@st.cache_data(show_spinner=False)
def avatar_data_uri(folder: str, name: str) -> str:
    """Base64 data: URI for an avatar image.

    st.column_config.ImageColumn (used inside st.dataframe, e.g. the "Avatar"
    column in Lịch Sử Trận / Bảng Tổng Hợp Tướng) does NOT reliably load a
    plain local file path — it needs a URL or a data: URI. st.image() (used
    for the big avatar in "Chi Tiết Tướng") is fine with a local path as-is,
    so this is only used for dataframe Avatar columns.
    """
    p = avatar_path(folder, name)
    if not p:
        return ""
    with open(p, "rb") as f:
        b64 = base64.b64encode(f.read()).decode("ascii")
    return f"data:image/png;base64,{b64}"


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------
# Everything lives in a Google Sheet (tabs "matches" and "players" — see
# store.py). Both start empty and only change when you add/delete something
# yourself — no synthetic/demo data is generated by default. Needs
# st.secrets["gcp_service_account"] + st.secrets["SHEET_ID"] configured
# (see README.md, "Deploy lên Internet").
if "gcp_service_account" not in st.secrets or "SHEET_ID" not in st.secrets:
    st.error(
        "Chưa cấu hình kết nối Google Sheets (thiếu secrets `gcp_service_account` / "
        "`SHEET_ID`). Xem hướng dẫn ở README.md, phần **Deploy lên Internet**."
    )
    st.stop()

match_df_all = store.load_matches()
accounts_all = store.load_players()
reports_all = store.load_reports()

# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------

with st.sidebar:
    st.markdown(
        f'<div class="brand-row"><span class="brand-emoji">🎮</span>'
        f'<span class="brand-name">{data.TEAM_NAME}</span></div>',
        unsafe_allow_html=True,
    )
    st.markdown("---")

    st.markdown("🌐 **Server**")
    server = st.selectbox(
        "Server", ["ALL"] + data.SERVERS, label_visibility="collapsed"
    )

    st.markdown("---")
    st.markdown("🗓️ **Khoảng thời gian**")
    default_end = datetime.now().date()
    default_start = default_end - timedelta(days=30)
    c1, c2 = st.columns(2)
    with c1:
        date_from = st.date_input("Từ ngày", value=default_start)
    with c2:
        date_to = st.date_input("Đến ngày", value=default_end)

    st.markdown("---")

    if "insight_idx" not in st.session_state:
        st.session_state.insight_idx = 0

    # Compute facts from the currently filtered team data (defined below via
    # a small pre-filter pass so the sidebar can show something meaningful).
    pre = match_df_all.copy()
    if server != "ALL":
        pre = pre[pre["server"] == server]
    pre = pre[(pre["date"] >= pd.Timestamp(date_from)) & (pre["date"] <= pd.Timestamp(date_to))]

    def build_facts(df: pd.DataFrame) -> list[str]:
        if df.empty:
            return ["Chưa có dữ liệu trong khoảng thời gian đã chọn."] * 5
        wr = data.kpi_winrate(df)
        kda = data.kpi_kda(df)
        total = len(df)
        top_player = df["player"].value_counts().idxmax()
        top_player_games = int(df["player"].value_counts().max())
        top_hero = df["hero"].value_counts().idxmax()
        top_hero_games = int(df["hero"].value_counts().max())
        mvp_rate = data.kpi_mvp_rate(df)
        active_days = df["date"].nunique()
        return [
            f"Form cực ổn — WinRate {wr:.2f}% trên tổng {total:,} lượt. "
            f"Giữ vững nhịp độ này! KDA trung bình {kda:.2f} cho thấy khả năng giao tranh xuất sắc.",
            f"{top_player} đang cày nhiều nhất đội với {top_player_games:,} lượt chơi trong khoảng thời gian này.",
            f"{top_hero} là tướng được chọn nhiều nhất ({top_hero_games:,} lượt). Đối thủ chắc đã quen mặt rồi!",
            f"Tỉ lệ MVP toàn đội đạt {mvp_rate:.1f}%. Cứ khoảng {max(1, round(100/max(mvp_rate,1)))} trận lại có một pha carry đỉnh cao.",
            f"Đội đã tập luyện {active_days} ngày trong khoảng đã chọn — trung bình {total/max(active_days,1):.1f} lượt/ngày.",
        ]

    facts = build_facts(pre)
    idx = st.session_state.insight_idx % len(facts)
    st.markdown(
        f"""
        <div class="insight-card">
            <div class="insight-title">🔎 Insight Bot</div>
            <div class="insight-text">{facts[idx]}</div>
            <div class="insight-fact">Fact {idx + 1}/{len(facts)}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )
    if st.button("🔄 Làm mới", use_container_width=True):
        st.session_state.insight_idx += 1
        st.rerun()

    st.markdown(
        f'<div class="footer-note">Timezone: {data.TIMEZONE_LABEL}<br/>Team Dashboard</div>',
        unsafe_allow_html=True,
    )

# ---------------------------------------------------------------------------
# Apply global filters (server + date range) used by every tab
# ---------------------------------------------------------------------------

df = match_df_all.copy()
if server != "ALL":
    df = df[df["server"] == server]
df = df[(df["date"] >= pd.Timestamp(date_from)) & (df["date"] <= pd.Timestamp(date_to))]

accounts = accounts_all.copy()
if server != "ALL":
    accounts = accounts[accounts["server"] == server]

reports = reports_all.copy()
if server != "ALL":
    players_on_server = set(accounts_all[accounts_all["server"] == server]["player"])
    reports = reports[reports["player"].isin(players_on_server)]
if not reports.empty:
    reports = reports[
        (reports["date"] >= pd.Timestamp(date_from)) & (reports["date"] <= pd.Timestamp(date_to))
    ]

# ---------------------------------------------------------------------------
# Tabs
# ---------------------------------------------------------------------------

(
    tab_overview,
    tab_players,
    tab_heroes,
    tab_history,
    tab_compare,
    tab_profile,
    tab_behavior,
    tab_rank,
) = st.tabs(
    [
        "📊 Tổng Quan",
        "👤 Tuyển Thủ",
        "⚔️ Tướng",
        "📋 Lịch Sử Trận",
        "🔀 So Sánh",
        "🪪 Hồ Sơ",
        "⚠️ Hành Vi",
        "🏆 Rank",
    ]
)


# ============================== TỔNG QUAN ==================================
with tab_overview:
    total_games = len(df)
    distinct_battles = df["battle_id"].nunique() if not df.empty else 0
    winrate = data.kpi_winrate(df)
    kda = data.kpi_kda(df)

    c1, c2, c3, c4 = st.columns(4)
    with c1:
        st.markdown(
            theme.kpi_card("Lượt Chơi", f"{total_games:,}", "COUNT(*)", theme.ACCENT_PURPLE),
            unsafe_allow_html=True,
        )
    with c2:
        st.markdown(
            theme.kpi_card(
                "Trận Riêng Biệt", f"{distinct_battles:,}", "COUNT(DISTINCT Battle(D))", theme.ACCENT_TEAL
            ),
            unsafe_allow_html=True,
        )
    with c3:
        st.markdown(
            theme.kpi_card("Tỉ Lệ Thắng", f"{winrate:.2f}%", "Win / TotalGames", theme.ACCENT_ORANGE),
            unsafe_allow_html=True,
        )
    with c4:
        st.markdown(
            theme.kpi_card("KDA", f"{kda:.2f}", "(K+A)/D", theme.ACCENT_YELLOW),
            unsafe_allow_html=True,
        )

    st.markdown("<br/>", unsafe_allow_html=True)
    theme.section_header("✅", "Biểu Đồ Tập Luyện Theo Ngày")
    if df.empty:
        st.info("Không có dữ liệu trong khoảng thời gian đã chọn.")
    else:
        daily = (
            df.groupby("date")
            .agg(games=("player", "count"), wins=("result", lambda s: (s == "Win").sum()))
            .reset_index()
        )
        daily["winrate"] = daily["wins"] / daily["games"] * 100
        st.plotly_chart(charts.daily_training_chart(daily), use_container_width=True)

    theme.section_header("🏆", "Top Tuyển Thủ")
    colA, colB = st.columns(2)
    with colA:
        st.markdown("**Khối Lượng Tập (Top 10)**")
        if not df.empty:
            top_vol = (
                df.groupby("player").size().reset_index(name="games").sort_values("games", ascending=False).head(10)
            )
            st.plotly_chart(
                charts.top_bar_chart(top_vol, "games", "player", theme.ACCENT_TEAL, "Lượt chơi"),
                use_container_width=True,
            )
    with colB:
        st.markdown("**KDA (Top 10)**")
        if not df.empty:
            top_kda = (
                df.groupby("player")
                .apply(lambda g: data.kpi_kda(g), include_groups=False)
                .reset_index(name="kda")
                .sort_values("kda", ascending=False)
                .head(10)
            )
            st.plotly_chart(
                charts.top_bar_chart(top_kda, "kda", "player", theme.ACCENT_PURPLE, "KDA"),
                use_container_width=True,
            )

    theme.section_header("🎖️", "Phân Bố Rank")
    if not accounts.empty:
        rank_order = {code: i for i, (code, _, _) in enumerate(data.RANK_TIERS)}
        rank_counts = accounts.groupby("rank_code")["player"].nunique().reset_index(name="count")
        rank_counts["order"] = rank_counts["rank_code"].map(rank_order)
        rank_counts = rank_counts.sort_values("order")
        rank_counts["rank_x"] = rank_counts["rank_code"].map(
            lambda c: f"{c} - {data.RANK_LOOKUP[c][0]}"
        )
        rank_counts["color"] = theme.ACCENT_PURPLE
        # Highlight the tier with the most players, like the original chart.
        if not rank_counts.empty:
            max_idx = rank_counts["count"].idxmax()
            rank_counts.loc[max_idx, "color"] = theme.ACCENT_TEAL
        st.plotly_chart(charts.rank_distribution_chart(rank_counts), use_container_width=True)


# ============================== TUYỂN THỦ ===================================
with tab_players:
    theme.section_header("👥", "Quản Lý Tuyển Thủ")

    rank_option_labels = [f"{code} - {label}" for code, label, _ in data.RANK_TIERS]

    with st.popover("➕ Thêm tuyển thủ / tài khoản mới"):
        st.markdown("**Nhập thông tin tuyển thủ**")
        with st.form("add_player_form", clear_on_submit=True):
            p_name = st.text_input("Tên tuyển thủ", key="add_p_name")
            p_server = st.selectbox("Server", data.SERVERS, key="add_p_server")
            p_account = st.text_input("Tên tài khoản", key="add_p_account")
            p_rank_label = st.selectbox("Rank hiện tại", rank_option_labels, key="add_p_rank")
            p_stars = st.number_input("Sao", min_value=0, value=0, step=1, key="add_p_stars")

            submitted_p = st.form_submit_button("💾 Lưu tuyển thủ", use_container_width=True)
            if submitted_p:
                if not p_name.strip() or not p_account.strip():
                    st.error("Cần nhập đủ Tên tuyển thủ và Tên tài khoản.")
                else:
                    p_rank_code = p_rank_label.split(" - ")[0]
                    store.add_player(
                        {
                            "player": p_name.strip(),
                            "server": p_server,
                            "account": p_account.strip(),
                            "rank_code": p_rank_code,
                            "rank_label": p_rank_label,
                            "stars": int(p_stars),
                        }
                    )
                    st.toast(f"Đã thêm tuyển thủ {p_name.strip()}!", icon="✅")
                    st.rerun()

    if accounts_all.empty:
        st.info("Chưa có tuyển thủ nào — bấm ➕ Thêm tuyển thủ / tài khoản mới ở trên để bắt đầu.")
    else:
        if "editing_player_id" not in st.session_state:
            st.session_state.editing_player_id = None

        col_widths = [1.2, 0.7, 1.1, 1.5, 0.5, 1.3, 0.45, 0.45]
        rcols = st.columns(col_widths)
        for col, h in zip(rcols, ["Tuyển thủ", "Server", "Tài khoản", "Rank", "Sao", "Cập nhật", "", ""]):
            col.markdown(f"**{h}**")
        st.markdown('<hr class="section-divider" />', unsafe_allow_html=True)

        for _, prow in accounts_all.iterrows():
            acc_id = int(prow["account_id"])
            rcols = st.columns(col_widths)
            rcols[0].write(prow["player"])
            rcols[1].write(prow["server"])
            rcols[2].write(prow["account"])
            rcols[3].write(prow["rank_label"])
            rcols[4].write(int(prow["stars"]))
            updated = prow["updated_at"]
            rcols[5].write(updated.strftime("%Y-%m-%d %H:%M") if pd.notna(updated) else "—")
            if rcols[6].button("✎", key=f"edit_player_{acc_id}", help="Sửa tuyển thủ này"):
                st.session_state.editing_player_id = None if st.session_state.editing_player_id == acc_id else acc_id
                st.rerun()
            if rcols[7].button("✕", key=f"del_player_{acc_id}", help="Xóa tuyển thủ này"):
                store.delete_player(acc_id)
                st.toast("Đã xóa tuyển thủ.", icon="🗑️")
                st.rerun()

            if st.session_state.editing_player_id == acc_id:
                with st.form(f"edit_player_form_{acc_id}"):
                    st.markdown(f"**✎ Sửa thông tin: {prow['player']}**")
                    e1, e2 = st.columns(2)
                    with e1:
                        e_name = st.text_input("Tên tuyển thủ", value=prow["player"], key=f"e_name_{acc_id}")
                        server_idx = data.SERVERS.index(prow["server"]) if prow["server"] in data.SERVERS else 0
                        e_server = st.selectbox("Server", data.SERVERS, index=server_idx, key=f"e_server_{acc_id}")
                        e_account = st.text_input("Tên tài khoản", value=prow["account"], key=f"e_account_{acc_id}")
                    with e2:
                        rank_idx = (
                            rank_option_labels.index(prow["rank_label"])
                            if prow["rank_label"] in rank_option_labels
                            else 0
                        )
                        e_rank_label = st.selectbox(
                            "Rank hiện tại", rank_option_labels, index=rank_idx, key=f"e_rank_{acc_id}"
                        )
                        e_stars = st.number_input(
                            "Sao", min_value=0, value=int(prow["stars"]), step=1, key=f"e_stars_{acc_id}"
                        )

                    ec1, ec2 = st.columns(2)
                    save_edit = ec1.form_submit_button("💾 Lưu thay đổi", use_container_width=True)
                    cancel_edit = ec2.form_submit_button("❌ Hủy", use_container_width=True)

                    if save_edit:
                        if not e_name.strip() or not e_account.strip():
                            st.error("Cần nhập đủ Tên tuyển thủ và Tên tài khoản.")
                        else:
                            e_rank_code = e_rank_label.split(" - ")[0]
                            store.update_player(
                                acc_id,
                                {
                                    "player": e_name.strip(),
                                    "server": e_server,
                                    "account": e_account.strip(),
                                    "rank_code": e_rank_code,
                                    "rank_label": e_rank_label,
                                    "stars": int(e_stars),
                                },
                            )
                            st.session_state.editing_player_id = None
                            st.toast(f"Đã cập nhật {e_name.strip()}!", icon="✅")
                            st.rerun()
                    if cancel_edit:
                        st.session_state.editing_player_id = None
                        st.rerun()

    theme.section_header("📋", "Bảng Tổng Hợp Tuyển Thủ")

    if df.empty:
        st.info("Không có dữ liệu trong khoảng thời gian đã chọn.")
    else:
        summary_rows = []
        for (player, acct_server, account), g in df.groupby(["player", "server", "account"]):
            summary_rows.append(
                {
                    "Tuyển thủ": player,
                    "Server": acct_server,
                    "Tài khoản": account,
                    "Lượt chơi": len(g),
                    "Ranked": int((g["mode"] == "Ranked").sum()),
                    "WR%": data.kpi_winrate(g),
                    "KDA": data.kpi_kda(g),
                    "MVP%": data.kpi_mvp_rate(g),
                    "Damage TB": g["damage"].mean(),
                    "Gold TB": g["gold"].mean(),
                    "Farm TB": g["farm"].mean(),
                }
            )
        summary_df = pd.DataFrame(summary_rows).sort_values("Lượt chơi", ascending=False)
        summary_df["KDA"] = summary_df["KDA"].round(2)
        for c in ["Damage TB", "Gold TB", "Farm TB"]:
            summary_df[c] = summary_df[c].round(0)
        st.dataframe(
            summary_df,
            use_container_width=True,
            hide_index=True,
            column_config={
                "WR%": st.column_config.ProgressColumn(
                    "WR%", format="%.1f%%", min_value=0, max_value=100
                ),
                "MVP%": st.column_config.ProgressColumn(
                    "MVP%", format="%.1f%%", min_value=0, max_value=100
                ),
                "Damage TB": st.column_config.NumberColumn("Damage TB", format="%d"),
                "Gold TB": st.column_config.NumberColumn("Gold TB", format="%d"),
                "Farm TB": st.column_config.NumberColumn("Farm TB", format="%d"),
            },
        )


# ================================= TƯỚNG ====================================
with tab_heroes:
    st.caption("⚠️ Hero analytics — dữ liệu của team, tất cả mode")
    st.caption("📊 Lượt chơi = COUNT(*) — player workload")

    theme.section_header("📋", "Bảng Tổng Hợp Tướng")

    if df.empty:
        st.info("Không có dữ liệu trong khoảng thời gian đã chọn.")
    else:
        hero_agg = (
            df.groupby("hero")
            .apply(
                lambda g: pd.Series(
                    {
                        "games": len(g),
                        "winrate": data.kpi_winrate(g),
                        "kda": data.kpi_kda(g),
                        "mvp": data.kpi_mvp_rate(g),
                    }
                ),
                include_groups=False,
            )
            .reset_index()
        )

        c1, c2, c3 = st.columns(3)
        with c1:
            st.markdown(
                theme.kpi_card("Tướng Được Chơi", f"{df['hero'].nunique()}", "", theme.ACCENT_PURPLE),
                unsafe_allow_html=True,
            )
        with c2:
            st.markdown(
                theme.kpi_card("Tổng Lượt Chơi", f"{len(df):,}", "", theme.ACCENT_TEAL),
                unsafe_allow_html=True,
            )
        with c3:
            hottest = hero_agg.sort_values("games", ascending=False).iloc[0]
            st.markdown(
                theme.kpi_card(
                    "Tướng Hot Nhất", hottest["hero"], f"{int(hottest['games'])} lượt", theme.ACCENT_TEAL
                ),
                unsafe_allow_html=True,
            )

        colA, colB = st.columns(2)
        with colA:
            st.markdown("**Top 15 — Pick Rate**")
            top_pick = hero_agg.sort_values("games", ascending=False).head(15)
            st.plotly_chart(
                charts.top_bar_chart(top_pick, "games", "hero", theme.ACCENT_TEAL, "Lượt chơi"),
                use_container_width=True,
            )
        with colB:
            st.markdown("**Top 15 — Win Rate (≥5 lượt)**")
            top_wr = hero_agg[hero_agg["games"] >= 5].sort_values("winrate", ascending=False).head(15)
            st.plotly_chart(
                charts.top_bar_chart(top_wr, "winrate", "hero", theme.ACCENT_PURPLE, "WinRate %"),
                use_container_width=True,
            )

        table = hero_agg.sort_values("games", ascending=False).copy()
        table["Avatar"] = table["hero"].apply(lambda h: avatar_data_uri(ASSETS_AVATARS, h))
        table = table.rename(
            columns={"hero": "Tướng", "games": "Lượt chơi", "winrate": "WR%", "kda": "KDA", "mvp": "MVP%"}
        )[["Avatar", "Tướng", "Lượt chơi", "WR%", "KDA", "MVP%"]]
        st.dataframe(
            table,
            use_container_width=True,
            hide_index=True,
            column_config={
                "Avatar": st.column_config.ImageColumn("Avatar", width="small"),
                "WR%": st.column_config.ProgressColumn("WR%", format="%.1f%%", min_value=0, max_value=100),
            },
        )

        theme.section_header("🔍", "Chi Tiết Tướng")
        heroes_in_view = sorted(df["hero"].unique())
        selected_hero = st.selectbox("Chọn tướng", heroes_in_view, key="hero_select")
        hdf = df[df["hero"] == selected_hero]

        colImg, colName = st.columns([1, 6])
        with colImg:
            path = avatar_path(ASSETS_AVATARS, selected_hero)
            if path:
                st.image(path, width=72)
        with colName:
            st.markdown(f"### {selected_hero}")

        c1, c2, c3, c4 = st.columns(4)
        with c1:
            st.markdown(theme.kpi_card("Lượt Chơi", f"{len(hdf)}", "", theme.ACCENT_PURPLE), unsafe_allow_html=True)
        with c2:
            st.markdown(
                theme.kpi_card("WinRate", f"{data.kpi_winrate(hdf):.2f}%", "", theme.ACCENT_RED),
                unsafe_allow_html=True,
            )
        with c3:
            st.markdown(theme.kpi_card("KDA", f"{data.kpi_kda(hdf):.2f}", "", theme.ACCENT_YELLOW), unsafe_allow_html=True)
        with c4:
            st.markdown(
                theme.kpi_card("MVP Rate", f"{data.kpi_mvp_rate(hdf):.2f}%", "", theme.ACCENT_TEAL),
                unsafe_allow_html=True,
            )

        st.markdown(f"**Xu Hướng — {selected_hero}**")
        daily_h = (
            hdf.groupby("date")
            .apply(
                lambda g: pd.Series({"games": len(g), "winrate": data.kpi_winrate(g)}), include_groups=False
            )
            .reset_index()
        )
        st.plotly_chart(charts.hero_trend_chart(daily_h), use_container_width=True)


# ============================ LỊCH SỬ TRẬN ==================================
with tab_history:
    st.caption("📄 Dữ liệu row-level từ Google Sheet (tab matches) — bạn tự thêm/xóa từng trận")

    # -------------------------- Thêm trận đấu mới ---------------------------
    roster_players_for_match = sorted(accounts_all["player"].unique()) if not accounts_all.empty else []

    if not roster_players_for_match:
        st.info(
            "Chưa có tuyển thủ nào trong danh sách — sang tab **👥 Tuyển Thủ** để "
            "thêm tuyển thủ / tài khoản trước khi nhập trận đấu."
        )
    else:
        with st.popover("➕ Thêm trận đấu mới", use_container_width=False):
            st.markdown("**Nhập thông tin trận đấu**")

            # Player + account chọn ngoài form để 2 ô này phản ứng với nhau
            # (tuyển thủ có thể có nhiều tài khoản/server khác nhau).
            pc1, pc2 = st.columns(2)
            with pc1:
                new_player = st.selectbox("Tuyển thủ", roster_players_for_match, key="add_player")
            player_accounts = accounts_all[accounts_all["player"] == new_player]
            account_option_labels = [
                f"{row['account']} ({row['server']})" for _, row in player_accounts.iterrows()
            ]
            with pc2:
                new_account_label = st.selectbox(
                    "Tài khoản", account_option_labels, key="add_account"
                )

            with st.form("add_match_form", clear_on_submit=True):
                fc1, fc2 = st.columns(2)
                with fc1:
                    new_date = st.date_input("Ngày", value=datetime.now().date(), key="add_date")
                    new_hero = st.selectbox("Tướng", data.HEROES, key="add_hero")
                    new_mode = st.selectbox("Mode", data.GAME_MODES, index=0, key="add_mode")  # mặc định Ranked
                    new_phe = st.selectbox("Phe", data.SIDES, key="add_phe")
                with fc2:
                    new_time = st.time_input(
                        "Giờ", value=datetime.now().time().replace(microsecond=0), key="add_time"
                    )
                    new_result_label = st.selectbox("Kết quả", ["1 - Thắng", "0 - Thua"], key="add_result")
                    new_level = st.number_input("Level", min_value=1, max_value=15, value=12, step=1, key="add_level")
                    new_mvp = st.checkbox("MVP", value=False, key="add_mvp")

                st.markdown("**Chỉ số trận đấu**")
                n1, n2, n3, n4 = st.columns(4)
                with n1:
                    new_kill = st.number_input("Kill", min_value=0, value=0, step=1, key="add_kill")
                    new_damage = st.number_input("Damage", min_value=0, value=50000, step=1000, key="add_damage")
                with n2:
                    new_death = st.number_input("Death", min_value=0, value=0, step=1, key="add_death")
                    new_gold = st.number_input("Gold", min_value=0, value=8000, step=100, key="add_gold")
                with n3:
                    new_assist = st.number_input("Assist", min_value=0, value=0, step=1, key="add_assist")
                    new_farm = st.number_input("Farm", min_value=0, value=25, step=1, key="add_farm")
                with n4:
                    new_phut = st.number_input("Phút", min_value=0, max_value=60, value=10, step=1, key="add_phut")
                    new_tru = st.number_input("Trụ", min_value=0, value=0, step=1, key="add_tru")

                submitted = st.form_submit_button("💾 Lưu trận đấu", use_container_width=True)
                if submitted:
                    acct_rows = accounts_all[accounts_all["player"] == new_player].reset_index(drop=True)
                    chosen_idx = account_option_labels.index(new_account_label) if new_account_label in account_option_labels else 0
                    if not acct_rows.empty:
                        acct = acct_rows.iloc[chosen_idx]
                        account, acct_server = acct["account"], acct["server"]
                        rank_code, rank_label = acct["rank_code"], acct["rank_label"]
                    else:
                        account, acct_server = "unknown", data.SERVERS[0]
                        rank_code = data.RANK_TIERS[0][0]
                        rank_label = f"{rank_code} - {data.RANK_TIERS[0][1]}"

                    new_dt = datetime.combine(new_date, new_time)
                    result_value = "Win" if new_result_label.startswith("1") else "Loss"

                    store.add_match(
                        {
                            "player": new_player,
                            "account": account,
                            "server": acct_server,
                            "datetime": new_dt.strftime("%Y-%m-%d %H:%M:%S"),
                            "hero": new_hero,
                            "mode": new_mode,
                            "result": result_value,
                            "phe": new_phe,
                            "phut": int(new_phut),
                            "kill": int(new_kill),
                            "death": int(new_death),
                            "assist": int(new_assist),
                            "damage": int(new_damage),
                            "gold": int(new_gold),
                            "farm": int(new_farm),
                            "tru": int(new_tru),
                            "level": int(new_level),
                            "mvp": bool(new_mvp),
                            "rank_code": rank_code,
                            "rank_label": rank_label,
                            "battle_id": None,
                        }
                    )
                    st.toast(f"Đã thêm trận đấu cho {new_player}!", icon="✅")
                    st.rerun()

    # ------------------------------- Bộ lọc ----------------------------------
    c1, c2, c3 = st.columns(3)
    players_options = ["Tất cả"] + sorted(df["player"].unique()) if not df.empty else ["Tất cả"]
    modes_options = ["Tất cả"] + data.GAME_MODES
    heroes_options = ["Tất cả"] + (sorted(df["hero"].unique()) if not df.empty else [])

    with c1:
        f_player = st.selectbox("Tuyển thủ", players_options)
    with c2:
        f_mode = st.selectbox("Game Mode", modes_options)
    with c3:
        f_hero = st.selectbox("Tướng", heroes_options)

    hist = df.copy()
    if f_player != "Tất cả":
        hist = hist[hist["player"] == f_player]
    if f_mode != "Tất cả":
        hist = hist[hist["mode"] == f_mode]
    if f_hero != "Tất cả":
        hist = hist[hist["hero"] == f_hero]

    hist = hist.sort_values("datetime", ascending=False)

    c1, c2, c3 = st.columns(3)
    with c1:
        st.markdown(
            theme.kpi_card("Tổng Số Trận", f"{len(hist):,}", "khớp bộ lọc", theme.ACCENT_PURPLE),
            unsafe_allow_html=True,
        )
    with c2:
        wins_shown = int((hist["result"] == "Win").sum())
        st.markdown(
            theme.kpi_card("Thắng", f"{wins_shown:,}", f"trong {len(hist):,} trận", theme.ACCENT_TEAL),
            unsafe_allow_html=True,
        )
    with c3:
        st.markdown(
            theme.kpi_card("WR", f"{data.kpi_winrate(hist):.1f}%", "trên dữ liệu đang lọc", theme.ACCENT_ORANGE),
            unsafe_allow_html=True,
        )

    # --------------------- Bảng quản lý (chọn dòng để xóa) --------------------
    if hist.empty:
        st.info("Không có trận nào khớp bộ lọc.")
    else:
        PAGE_SIZE = 20
        total_rows = len(hist)
        total_pages = max(1, -(-total_rows // PAGE_SIZE))

        if "history_page" not in st.session_state:
            st.session_state.history_page = 1
        st.session_state.history_page = max(1, min(st.session_state.history_page, total_pages))

        start = (st.session_state.history_page - 1) * PAGE_SIZE
        page_df = hist.iloc[start : start + PAGE_SIZE].reset_index(drop=True).copy()

        page_df["Avatar"] = page_df["hero"].apply(lambda h: avatar_data_uri(ASSETS_AVATARS, h))
        page_df["Kết quả"] = page_df["result"].apply(lambda r: "🟢 1" if r == "Win" else "🔴 0")
        page_df["MVP"] = page_df["mvp"].apply(lambda v: "✅" if bool(v) else "—")
        page_df["Thời gian"] = page_df["datetime"].dt.strftime("%Y-%m-%d %H:%M")
        page_df["Damage"] = page_df["damage"].apply(lambda v: f"{int(v):,}")
        page_df["Gold"] = page_df["gold"].apply(lambda v: f"{int(v):,}")

        display_df = page_df.rename(
            columns={
                "player": "Tuyển thủ",
                "hero": "Tướng",
                "mode": "Mode",
                "phe": "Phe",
                "phut": "Phút",
                "kill": "Kill",
                "death": "Death",
                "assist": "Assist",
                "farm": "Farm",
                "tru": "Trụ",
                "level": "Level",
            }
        )[
            [
                "match_id", "Tuyển thủ", "Thời gian", "Avatar", "Tướng", "Mode",
                "Kết quả", "Phe", "Phút", "Kill", "Death", "Assist", "Damage",
                "Gold", "Farm", "Trụ", "Level", "MVP",
            ]
        ]

        st.caption("💡 Bấm chọn 1 dòng trong bảng để hiện nút xóa trận đó.")
        event = st.dataframe(
            display_df,
            use_container_width=True,
            hide_index=True,
            column_config={
                "match_id": None,  # id nội bộ, không hiển thị nhưng dùng để xóa
                "Avatar": st.column_config.ImageColumn("Avatar", width="small"),
            },
            on_select="rerun",
            selection_mode="single-row",
            key=f"history_table_{st.session_state.history_page}",
        )

        sel_rows = []
        if event is not None:
            try:
                sel_rows = list(event["selection"]["rows"])
            except (KeyError, TypeError):
                sel_rows = []
        if sel_rows:
            sel_match_id = int(display_df.iloc[sel_rows[0]]["match_id"])
            dcol1, dcol2 = st.columns([1, 5])
            with dcol1:
                if st.button("✕ Xóa trận đã chọn", key=f"del_hist_{sel_match_id}"):
                    store.delete_match(sel_match_id)
                    st.toast("Đã xóa trận đấu.", icon="🗑️")
                    st.rerun()

        pc1, pc2, pc3 = st.columns([1, 2, 1])
        with pc1:
            if st.button("◀ Trước", disabled=st.session_state.history_page <= 1, use_container_width=True):
                st.session_state.history_page -= 1
                st.rerun()
        with pc2:
            st.markdown(
                f'<div style="text-align:center;color:{theme.TEXT_MUTED};padding-top:6px;">'
                f"Trang {st.session_state.history_page}/{total_pages} — {total_rows:,} trận</div>",
                unsafe_allow_html=True,
            )
        with pc3:
            if st.button(
                "Sau ▶", disabled=st.session_state.history_page >= total_pages, use_container_width=True
            ):
                st.session_state.history_page += 1
                st.rerun()


# ================================ SO SÁNH ===================================
with tab_compare:
    st.caption("📄 Radar chart so sánh — dữ liệu từ report_player_daily")

    if df.empty:
        st.info("Không có dữ liệu trong khoảng thời gian đã chọn.")
    else:
        roster = sorted(df["player"].unique())
        default_sel = roster[:2] if len(roster) >= 2 else roster
        selected_players = st.multiselect(
            "Chọn 2-5 tuyển thủ", roster, default=default_sel, max_selections=5
        )

        if len(selected_players) < 2:
            st.info("Chọn ít nhất 2 tuyển thủ để so sánh.")
        else:
            theme.section_header("📈", "So Sánh Chỉ Số (normalized 0-100)")

            # Base stats for every player in view (used both for the raw table
            # and to min-max normalize the radar so it stays meaningful team-wide).
            stats = []
            for p, g in df.groupby("player"):
                stats.append(
                    {
                        "player": p,
                        "games": len(g),
                        "WinRate %": data.kpi_winrate(g),
                        "KDA": data.kpi_kda(g),
                        "MVP %": data.kpi_mvp_rate(g),
                        "Damage TB": g["damage"].mean(),
                        "Gold TB": g["gold"].mean(),
                        "Farm TB": g["farm"].mean(),
                    }
                )
            stats_df = pd.DataFrame(stats)

            axes = ["MVP %", "KDA", "WinRate %", "Farm TB", "Gold TB", "Damage TB"]
            norm_rows = []
            for _, row in stats_df.iterrows():
                norm = {"player": row["player"]}
                for a in axes:
                    lo, hi = stats_df[a].min(), stats_df[a].max()
                    norm[a] = 50.0 if hi == lo else float((row[a] - lo) / (hi - lo) * 100)
                norm_rows.append(norm)
            norm_df = pd.DataFrame(norm_rows).set_index("player")

            radar_rows = [
                {"player": p, **{a: norm_df.loc[p, a] for a in axes}}
                for p in selected_players
                if p in norm_df.index
            ]
            st.plotly_chart(charts.compare_radar_chart(radar_rows, axes), use_container_width=True)

            theme.section_header("📋", "Bảng Số Liệu Gốc")
            raw = stats_df[stats_df["player"].isin(selected_players)].copy()
            raw = raw.rename(columns={"player": "Tuyển thủ", "games": "Lượt chơi"})
            raw = raw[["Tuyển thủ", "Lượt chơi", "WinRate %", "KDA", "MVP %", "Damage TB", "Gold TB", "Farm TB"]]
            for col in ["WinRate %", "MVP %"]:
                raw[col] = raw[col].round(1)
            for col in ["KDA"]:
                raw[col] = raw[col].round(2)
            for col in ["Damage TB", "Gold TB", "Farm TB"]:
                raw[col] = raw[col].round(0)
            st.dataframe(
                raw.rename(columns={"WinRate %": "WR%", "MVP %": "MVP%"}),
                use_container_width=True,
                hide_index=True,
                column_config={
                    "WR%": st.column_config.ProgressColumn("WR%", format="%.1f%%", min_value=0, max_value=100)
                },
            )


# ================================= HỒ SƠ ====================================
with tab_profile:
    st.caption("🪪 Hồ sơ tuyển thủ — chi tiết theo từng người, hero pool và lịch sử theo ngày")

    roster_players = sorted(accounts_all["player"].unique()) if not accounts_all.empty else []
    all_players_in_view = sorted(df["player"].unique()) if not df.empty else roster_players
    if not all_players_in_view:
        all_players_in_view = roster_players

    if not all_players_in_view:
        st.info("Chưa có tuyển thủ nào — sang tab 👤 Tuyển Thủ để thêm tuyển thủ trước.")
        selected_player = None
        pdf = df
    else:
        selected_player = st.selectbox("Chọn tuyển thủ", all_players_in_view, key="profile_player_select")
        pdf = df[df["player"] == selected_player] if not df.empty else df

    if selected_player is None:
        pass
    elif pdf.empty:
        st.info("Tuyển thủ này chưa có dữ liệu trong khoảng thời gian đã chọn.")
    else:
        active_days = pdf["date"].nunique()
        c1, c2, c3, c4, c5, c6 = st.columns(6)
        with c1:
            st.markdown(
                theme.kpi_card("Lượt Chơi", f"{len(pdf):,}", f"{active_days} ngày tập", theme.ACCENT_PURPLE),
                unsafe_allow_html=True,
            )
        with c2:
            st.markdown(
                theme.kpi_card(
                    "Ranked", f"{int((pdf['mode'] == 'Ranked').sum()):,}", "", theme.ACCENT_BLUE
                ),
                unsafe_allow_html=True,
            )
        with c3:
            st.markdown(
                theme.kpi_card("Hero Pool", f"{pdf['hero'].nunique()}", "tướng đã dùng", theme.ACCENT_ORANGE),
                unsafe_allow_html=True,
            )
        with c4:
            st.markdown(
                theme.kpi_card("Win Rate", f"{data.kpi_winrate(pdf):.2f}%", "", theme.ACCENT_RED),
                unsafe_allow_html=True,
            )
        with c5:
            st.markdown(
                theme.kpi_card("KDA", f"{data.kpi_kda(pdf):.2f}", "", theme.ACCENT_YELLOW),
                unsafe_allow_html=True,
            )
        with c6:
            st.markdown(
                theme.kpi_card("MVP", f"{data.kpi_mvp_rate(pdf):.2f}%", "", theme.ACCENT_TEAL),
                unsafe_allow_html=True,
            )

        theme.section_header("🎯", "Hero Pool")
        hero_pool = (
            pdf.groupby("hero")
            .apply(
                lambda g: pd.Series(
                    {
                        "games": len(g),
                        "winrate": data.kpi_winrate(g),
                        "kda": data.kpi_kda(g),
                        "mvp": data.kpi_mvp_rate(g),
                    }
                ),
                include_groups=False,
            )
            .reset_index()
            .sort_values("games", ascending=False)
        )
        hero_pool["Avatar"] = hero_pool["hero"].apply(lambda h: avatar_data_uri(ASSETS_AVATARS, h))
        hero_pool = hero_pool.rename(
            columns={"hero": "Tướng", "games": "Trận", "winrate": "WR%", "kda": "KDA", "mvp": "MVP%"}
        )[["Avatar", "Tướng", "Trận", "WR%", "KDA", "MVP%"]]
        st.dataframe(
            hero_pool,
            use_container_width=True,
            hide_index=True,
            column_config={
                "Avatar": st.column_config.ImageColumn("Avatar", width="small"),
                "WR%": st.column_config.ProgressColumn("WR%", format="%.1f%%", min_value=0, max_value=100),
                "KDA": st.column_config.NumberColumn("KDA", format="%.2f"),
                "MVP%": st.column_config.ProgressColumn("MVP%", format="%.1f%%", min_value=0, max_value=100),
            },
        )

        theme.section_header("📈", "Lịch Sử")
        daily_mode = (
            pdf.groupby("date")
            .apply(
                lambda g: pd.Series(
                    {
                        "ranked": int((g["mode"] == "Ranked").sum()),
                        "normal": int((g["mode"] != "Ranked").sum()),
                        "winrate": data.kpi_winrate(g),
                    }
                ),
                include_groups=False,
            )
            .reset_index()
        )
        colL, colR = st.columns(2)
        with colL:
            st.markdown("**Lượt Chơi Theo Ngày**")
            st.plotly_chart(charts.mode_split_area_chart(daily_mode), use_container_width=True)
        with colR:
            st.markdown("**WinRate Theo Ngày**")
            st.plotly_chart(charts.winrate_line_chart(daily_mode), use_container_width=True)

        theme.section_header("🏅", "Rank Hiện Tại")
        p_accounts = accounts[accounts["player"] == selected_player].copy()
        if p_accounts.empty:
            st.info("Không có tài khoản nào cho tuyển thủ này.")
        else:
            p_accounts["Cập nhật"] = p_accounts["updated_at"].dt.strftime("%Y-%m-%d %H:%M:%S")
            show = p_accounts.rename(
                columns={"server": "Server", "account": "Tài khoản", "rank_label": "Rank", "stars": "Sao"}
            )[["Server", "Tài khoản", "Rank", "Sao", "Cập nhật"]].sort_values("Cập nhật", ascending=False)
            st.dataframe(show, use_container_width=True, hide_index=True)


# ================================ HÀNH VI ===================================
with tab_behavior:
    st.caption("⚠️ Report hành vi trong trận — 100% nhập tay, không tự sinh dữ liệu")

    roster_players_for_report = sorted(accounts_all["player"].unique()) if not accounts_all.empty else []

    if not roster_players_for_report:
        st.info(
            "Chưa có tuyển thủ nào trong danh sách — sang tab **👤 Tuyển Thủ** để "
            "thêm tuyển thủ trước khi nhập report."
        )
    else:
        with st.popover("➕ Thêm report mới"):
            st.markdown("**Nhập report hành vi**")
            with st.form("add_report_form", clear_on_submit=True):
                r_player = st.selectbox("Tuyển thủ bị report", roster_players_for_report, key="add_r_player")
                r_type = st.selectbox("Loại report", data.REPORT_TYPES, key="add_r_type")
                r_date = st.date_input("Ngày", value=datetime.now().date(), key="add_r_date")

                submitted_r = st.form_submit_button("💾 Lưu report", use_container_width=True)
                if submitted_r:
                    store.add_report(
                        {
                            "player": r_player,
                            "report_type": r_type,
                            "date": r_date.strftime("%Y-%m-%d"),
                        }
                    )
                    st.toast(f"Đã thêm report {r_type} cho {r_player}!", icon="✅")
                    st.rerun()

    if not reports_all.empty:
        with st.expander("🗑️ Xóa toàn bộ report"):
            confirm_wipe_r = st.checkbox("Tôi chắc chắn muốn xóa toàn bộ report hành vi", key="confirm_wipe_reports")
            if st.button("Xóa toàn bộ report", disabled=not confirm_wipe_r):
                store.clear_all_reports()
                st.toast("Đã xóa toàn bộ report.", icon="🗑️")
                st.rerun()

    total_reports = len(reports)
    type_counts = reports["report_type"].value_counts() if not reports.empty else pd.Series(dtype=int)

    kpi_cols = st.columns(len(data.REPORT_TYPES) + 1)
    with kpi_cols[0]:
        st.markdown(
            theme.kpi_card("TỔNG", f"{total_reports:,}", "report", theme.ACCENT_RED),
            unsafe_allow_html=True,
        )
    for i, rtype in enumerate(data.REPORT_TYPES, start=1):
        with kpi_cols[i]:
            st.markdown(
                theme.kpi_card(
                    rtype, f"{int(type_counts.get(rtype, 0)):,}", "",
                    data.REPORT_TYPE_COLORS.get(rtype, theme.ACCENT_PURPLE),
                ),
                unsafe_allow_html=True,
            )

    if reports.empty:
        st.info("Không có report nào trong khoảng thời gian / server đã chọn.")
    else:
        colL, colR = st.columns([2, 1])
        with colL:
            theme.section_header("📊", "Report Theo Ngày")
            daily_r = (
                reports.groupby(["date", "report_type"]).size().reset_index(name="count")
            )
            daily_r = daily_r.pivot(index="date", columns="report_type", values="count").fillna(0).reset_index()
            st.plotly_chart(
                charts.report_stacked_bar_chart(daily_r, data.REPORT_TYPES, data.REPORT_TYPE_COLORS),
                use_container_width=True,
            )
        with colR:
            theme.section_header("🍩", "Phân Bố")
            dist = reports["report_type"].value_counts().reindex(data.REPORT_TYPES).fillna(0)
            st.plotly_chart(
                charts.donut_chart(
                    dist.index.tolist(), dist.values.tolist(),
                    [data.REPORT_TYPE_COLORS.get(t, theme.ACCENT_PURPLE) for t in dist.index],
                ),
                use_container_width=True,
            )

        theme.section_header("👥", "Theo Tuyển Thủ")
        pivot = reports.groupby(["player", "report_type"]).size().unstack(fill_value=0)
        for t in data.REPORT_TYPES:
            if t not in pivot.columns:
                pivot[t] = 0
        pivot = pivot[data.REPORT_TYPES]
        pivot["Tổng"] = pivot.sum(axis=1)
        pivot = pivot.sort_values("Tổng", ascending=False).reset_index()
        pivot = pivot.rename(columns={"player": "Tuyển thủ"})[["Tuyển thủ", "Tổng"] + data.REPORT_TYPES]
        st.dataframe(pivot, use_container_width=True, hide_index=True)

    theme.section_header("📋", "Danh Sách Report")
    if reports_all.empty:
        st.info("Chưa có report nào.")
    else:
        rlist = reports_all.sort_values("date", ascending=False).reset_index(drop=True).copy()
        rlist["Ngày"] = rlist["date"].dt.strftime("%Y-%m-%d")
        rlist_display = rlist.rename(columns={"player": "Tuyển thủ", "report_type": "Loại report"})[
            ["report_id", "Tuyển thủ", "Loại report", "Ngày"]
        ]
        st.caption("💡 Bấm chọn 1 dòng trong bảng để hiện nút xóa report đó.")
        r_event = st.dataframe(
            rlist_display,
            use_container_width=True,
            hide_index=True,
            column_config={"report_id": None},
            on_select="rerun",
            selection_mode="single-row",
            key="reports_table",
        )
        r_sel_rows = []
        if r_event is not None:
            try:
                r_sel_rows = list(r_event["selection"]["rows"])
            except (KeyError, TypeError):
                r_sel_rows = []
        if r_sel_rows:
            sel_report_id = int(rlist_display.iloc[r_sel_rows[0]]["report_id"])
            if st.button("✕ Xóa report đã chọn", key=f"del_report_{sel_report_id}"):
                store.delete_report(sel_report_id)
                st.toast("Đã xóa report.", icon="🗑️")
                st.rerun()


# ================================== RANK ====================================
with tab_rank:
    st.caption("🏆 Rank hiện tại của toàn đội")

    if accounts.empty:
        st.info("Chưa có tuyển thủ nào.")
    else:
        rank_order = {code: i for i, (code, _, _) in enumerate(data.RANK_TIERS)}

        colL, colR = st.columns([1, 2])
        with colL:
            theme.section_header("🍩", "Phân Bố Rank")
            rank_dist = accounts.groupby("rank_code")["player"].nunique().reset_index(name="count")
            rank_dist["order"] = rank_dist["rank_code"].map(rank_order)
            rank_dist = rank_dist.sort_values("order")
            rank_dist["label"] = rank_dist["rank_code"].map(lambda c: f"{c} - {data.RANK_LOOKUP[c][0]}")
            st.plotly_chart(
                charts.donut_chart(rank_dist["label"].tolist(), rank_dist["count"].tolist()),
                use_container_width=True,
            )
        with colR:
            theme.section_header("📋", "Danh Sách Rank")
            show_rank = accounts.copy()
            show_rank["order"] = show_rank["rank_code"].map(rank_order)
            show_rank = show_rank.sort_values(["order", "stars"], ascending=[True, False])
            show_rank["Cập nhật lần cuối"] = show_rank["updated_at"].dt.strftime("%Y-%m-%d %H:%M:%S")
            show_rank = show_rank.rename(
                columns={
                    "player": "Tuyển thủ", "server": "Server", "account": "Tài khoản",
                    "rank_label": "Rank", "stars": "Sao",
                }
            )[["Tuyển thủ", "Server", "Tài khoản", "Rank", "Sao", "Cập nhật lần cuối"]]
            st.dataframe(show_rank, use_container_width=True, hide_index=True)
